agent_version: "0.1.0"
agent_id: ""
watch_directories:
  - "/home/vmadmin/test"

blacklist_paths:
  - "/proc"
  - "/sys"
  - "/dev"
  - "/tmp"

kafka:
  broker: "192.168.110.60:9092"
  topics:
    events: "agent-events"
    control: "agent-lifecycle"


heartbeat_interval_s: 60

log_level: "INFO"

# Optional: Parameter f√ºr Detektoren / Monitor
mass_create_window_s: 5
mass_create_threshold: 50
cooldown_seconds: 2 # Verhindert das bei jedem Memory modification ein Alert getriggert wird
entropy_abs_threshold: 7.2
entropy_min_size_bytes: 512
entropy_sample_each: 4096

